// Generated by CoffeeScript 1.11.1
(function() {
  jQuery(function($) {
    $('.wrap').on("click", "#callback-button", function() {
      $(".callbackForm").show(200);
      return $('.close-callback').show(200);
    });
    $('.wrap').on("click", ".close-callback", function() {
      $(this).slideToggle(200);
      return $(".callbackForm").hide(200);
    });
    return $("#callback-phone").mask("380(99) 999-99-99");
  });

}).call(this);

//# sourceMappingURL=callback.js.map
