// Generated by CoffeeScript 1.11.1
(function() {
  jQuery(function($) {
    var newHash, subSub;
    newHash = window.location.hash;
    if (newHash) {
      subSub = newHash.split('/')[0];
      return window.scrollTo(0, $("#kuhonnye-plity-i-poverhnosti-bu").offset().top - 100);
    }
  });

}).call(this);

//# sourceMappingURL=category.js.map
