// Generated by CoffeeScript 1.11.1
(function() {
  jQuery(function($) {
    return $(window).scroll(function() {
      var scrollTop, threshold, topHeader;
      topHeader = $('.header-scroll-hide');
      scrollTop = $(this).scrollTop();
      threshold = $(".header-scroll-show").height() - 170;
      if (scrollTop > threshold && !topHeader.hasClass('active')) {
        topHeader.addClass('active');
      }
      if (scrollTop < threshold && topHeader.hasClass('active')) {
        return topHeader.removeClass('active');
      }
    });
  });

}).call(this);

//# sourceMappingURL=header.js.map
