// Generated by CoffeeScript 1.11.1
(function() {
  jQuery(function($) {
    var headerphone;
    headerphone = $(".upper-phone-list");
    return headerphone.click(function(e) {
      e.stopPropagation();
      return $(this).toggleClass("show");
    });
  });

}).call(this);

//# sourceMappingURL=header.js.map
